### ISSUE TITLE
How to disable the autocompletion of nvim-ipy

### ISSUE THREAD

**Issue by d0u9** [bfredl/nvim-ipy#10]
When I active `nvim-ipy`, `YCM` seems be disabled, and I can't auto-complete the methods or members of class via YCM. Is there a way that the `YCM` and  `nvim-ipy` can work cooperatively?

**Comment by bfredl** [comment]
Weird, since `nvim-ipy` doesn't mess with any complete options at all, only thing `nvim-ipy` does is to define the mapping
`inoremap <Plug>(IPy-Complete) <c-o>:<c-u>call IPyComplete()<cr>`
and if the mapping is not invoked by user there should be no way it could disturb YCM. But I have only tested with using vim-jedi directly, I will try test with YCM. 
(To actually _integrate_ with YCM will require more work, but shouldn't be too hard if YCM allows completions to be pushed asynchronously from vimscript.)

**Comment by d0u9** [comment]
I don't know why, even the jupyter window is closed by `:q`. YCM can not still work, until I entirely close vim and restart it. 

The default YCM completion key bind `<C-Space>` doesn't work as well when jupyter window opens.

**Comment by bfredl** [comment]
Sorry, cannot reproduce. I get the YCM popup as expected ( and can switch to nvim-ipy completion by `<Plug>(IPy-Complete)`)  Would you mind sharing your nvimrc or relevant parts thereof (complete,YCM and nvim-ipy options) ?

**Comment by d0u9** [comment]
I reinstall all my plugins, the problem disappears.... I don't know why..
